### ISSUE TITLE
Unable to initiate 'class no.difi.vefa.peppol.security.util.DifiCertificateValidator' for lookup

### ISSUE THREAD

**Issue by martin-win** [OxalisCommunity/vefa-peppol#32]
I tried to follow the instructions in the readme to do a participant lookup but end up with the DifiCertificatevalidator exception. Does it require anything that's not written there? New to all these. Any help is appreciated. Thanks

 LookupClient client = LookupClientBuilder.forProduction()
                    .fetcher(ApacheFetcher.class)
                    .build();
List<DocumentTypeIdentifier> documentTypeIdentifiers = client.getDocumentIdentifiers(
                    ParticipantIdentifier.of("9908:810418052"));

**Comment by aaron-kumar** [comment]
Can you add bit more details?

Only thing, I can see that "Endpoint '9908:810418052' Certificate is no longer valid"

**Comment by aaron-kumar** [comment]
9908:810418052 is no longer valid i.e. endpoint certificate is already expired. Please comment if you face similar issue with any other valid endpoint. Closing issue for now.
