### ISSUE TITLE
Party Identifier (ICD) 0208 is missing in PeppolIcd enumeration

### ISSUE THREAD

**Issue by DraganDordevic** [OxalisCommunity/vefa-peppol#33]
Party Identifiers (ICD) 0201, 0202, 0204 and 0208 are missing in no.difi.vefa.peppol.icd.code.PeppolIcd (peppol-icd-1.1.4) even though it could be found in the corresponding list at https://docs.peppol.eu/poacc/billing/3.0/codelist/ICD/

**Comment by oxalis-update-info** [comment]
Added as part of commit: dda05d84a9d5a2ee1800c6be603ea0186b915368 .  Will be available in upcoming release.

**Comment by aaron-kumar** [comment]
Added as part of commit: dda05d84a9d5a2ee1800c6be603ea0186b915368 . Will be available in upcoming release.
