### ISSUE TITLE
Add support for SMP redirects

### ISSUE THREAD

**Issue by FrodeBjerkholt** [OxalisCommunity/vefa-peppol#36]
It would be nice to have support for SMP redirects in the LookupClient (see [SMP spesification](https://docs.peppol.eu/edelivery/smp/ICT-Transport-SMP_Service_Specification-110.pdf))

Philip Helger has implemented this in his [smp-client](https://github.com/phax/peppol-commons/tree/master/peppol-smp-client) if you want some code to look at.

**Comment by aaron-kumar** [comment]
Thanks for reporting this @FrodeBjerkholt .

Yes, Service Metadata Publisher Redirection at one level/degree is one of the valid use case. We will prioritize this requirement but please feel free to raise Pull Request (PR) if you can. Thanks !!!

**Comment by FrodeBjerkholt** [comment]
I am working on a PR now. Hopefully I have something ready for a review later this week.

**Comment by aaron-kumar** [comment]
Thanks @FrodeBjerkholt  👍 for contribution.
Commit# ddda09aa89596a18ffbec18f0d2293a889e37683 Merged
