### ISSUE TITLE
Party Identifier (ICD) 0209 is missing in PeppolIcd enumeration

### ISSUE THREAD

**Issue by javierestevez** [OxalisCommunity/vefa-peppol#37]
Party Identifier (ICD) 0209 is missing in no.difi.vefa.peppol.icd.code.PeppolIcd (master). This was added in the 3.0.8 release of the schematron (https://docs.peppol.eu/poacc/billing/3.0/release-notes/) but has not yet been added to the OpenPEPPOL eDEC Code Lists.

**Comment by aaron-kumar** [comment]
@javierestevez  , we are following OpenPeppol eDEC Code List: https://docs.peppol.eu/edelivery/codelists/ for routing. 
ICD 0209 is Not there in published version of "Participant Identifier Schemes v7.3" : https://docs.peppol.eu/edelivery/codelists/ 

If it will be added in v7.4 or v7.5 of OpenPeppol eDEC Code List (which is expected to published soon) then we will add support for it vefa-peppol version 2.0.0 and Oxalis version 5.0.0.

For general topic, you can make use of GitHub discussion now: "https://github.com/OxalisCommunity/vefa-peppol/discussions" .

For all Oxalis users, you can now start discussion on any important topic in "Discussions" section. If we agree that something need to fixed then you can create issue for that. 

Looking forward for support from your side. Thanks for being active player !!!

**Comment by javierestevez** [comment]
@aaron-kumar Thank you for the information. I have opened a ticket at OpenPEPPOL.

Regarding the discussions, do you mean that before reporting an issue we need to start a discussion and have the issue report approved? How is that better than reporting the issue directly and closing it if it is not pertinent?

Cheers,
Javier

**Comment by aaron-kumar** [comment]
@javierestevez If you are sure that there is an issue and provided complete information to reproduce it then please go ahead and open an issue directly. 
But if there is any confusion and discussion is required for that then use discussion channel. I hope that clarified the usage.

**Comment by javierestevez** [comment]
Ok, got it. Thanks!

**Comment by javierestevez** [comment]
Just a heads up. I just got a confirmation from Philip Helger at OpenPEPPOL that code 0209 will be part of the code list v7.5, hopefully available around end of April. Cheers.

**Comment by aaron-kumar** [comment]
Oxalis 5.0.1 released (https://github.com/OxalisCommunity/oxalis/releases/tag/v5.0.1) . 
ICD code 0209 (GS1) is included)
