### ISSUE TITLE
Exception in BusdoxReader.java:138

### ISSUE THREAD

**Issue by mindaugasjaugelis** [OxalisCommunity/vefa-peppol#41]
Getting null exception in BusdoxReader.java:138, there is probably incorect null check:
`endpointType.getService**Activation**Date() == null ? 
   null : endpointType.getService**Expiration**Date().toGregorianCalendar().getTime()`
Had to be endpointType.getServiceExpirationDate() checked for null?
https://github.com/OxalisCommunity/vefa-peppol/blob/master/peppol-lookup/src/main/java/network/oxalis/vefa/peppol/lookup/reader/BusdoxReader.java#L138

**Comment by aaron-kumar** [comment]
Nice catch @mindaugasjaugelis !!!
Fixed with commit # 84fd271aecbeb5accbfbf9bc1c98639e7f3122e4

**Comment by aaron-kumar** [comment]
Oxalis 5.0.1 released (https://github.com/OxalisCommunity/oxalis/releases/tag/v5.0.1)
