### ISSUE TITLE
Comparison for ServiceActivationDate und ServiceExpirationDate does not match Peppol rules

### ISSUE THREAD

**Issue by klaus-lue** [OxalisCommunity/vefa-peppol#44]
According to the Peppol Migration Document sent out on 2022-01-24 the ServiceActivationDate and ServiceExpirationDate need to be interpreted with >= and <= including also the seconds of the provided date.

The Migration Guide specifies it as:

> SMP client implementations are now forced to interpret these fields
accordingly
o The need to reject endpoints that are not yet active
(ServiceActivationDate is provided AND ServiceActivationDate is after
now).
o The need to reject endpoints that are no longer active
(ServiceExpirationDate is provided and before now).
o In all other cases, the endpoint needs to be accepted.
o Note: the values of “ServiceActivationDate” and
“ServiceExpirationDate” that exactly match the current date and time
(up to second precision) are considered to be “valid endpoint”
timestamps.

Compare the current implementation: https://github.com/OxalisCommunity/vefa-peppol/blame/938b0a1b33db549a3d361fc5f912fb40d75e86b4/peppol-common/src/main/java/network/oxalis/vefa/peppol/common/model/Period.java#L20

**Comment by aaron-kumar** [comment]
Thanks @klaus-lue  for posting. 
This change is part of Oxalis roadmap : https://github.com/orgs/OxalisCommunity/projects/12. 
This functionality will be released in early March, 2022

**Comment by aaron-kumar** [comment]
Changes committed as part of https://github.com/OxalisCommunity/vefa-peppol/commit/96be12a493f88ff072e197837cc05e67245145cc

**Comment by aaron-kumar** [comment]
Changes available in Oxalis release : v5.1.0
