### ISSUE TITLE
TransportProfile AS4 refers to ESENS_AS4, but should it refer to PEPPOL_AS4_2_0

### ISSUE THREAD

**Issue by WimMaerevoet-Octopus** [OxalisCommunity/vefa-peppol#53]
Not sure where to make the issue ( vefa-peppol or oxalis-as4 )

We are busy implementing reporting requirements and use the InboundMetaData to collect the transportProfile.
In Oxalis-AS4 , the transport profile is hardcoded to TransportProfile.AS4, which corresponds to "bdxr-transport-ebms3-as4-v1p0"

I would expect "peppol-transport-as4-v2_0" - TransportProfile.PEPPOL_AS4_2_0

**Comment by aaron-kumar** [comment]
Fixed with https://github.com/OxalisCommunity/vefa-peppol/commit/a7efc708f1dae5bf1a0cccafd47aa2056b09c026
