### ISSUE TITLE
BdxlLocator and BusdoxLocator reports network-level erros as "participant not found"

### ISSUE THREAD

**Issue by steinarhenriksen** [OxalisCommunity/vefa-peppol#56]
BdxlLocator and BusdoxLocator reports network-level erros as if the participant was not found, for example: `Identifier '0192:992090006' is not registered in SML`

I believe this to be a real and significant issue.

Incorrectly reporting network-level errors as participant not found is causing service providers operational issues. These issues have been present for a long while and is causing service providers to lose trust in the network and the SMPs.

Please examine the following lines of code:

https://github.com/OxalisCommunity/vefa-peppol/blob/8b3d3f01993accd35fb58959553203d38a98bd38/peppol-lookup/src/main/java/network/oxalis/vefa/peppol/lookup/locator/BdxlLocator.java#L155

https://github.com/OxalisCommunity/vefa-peppol/blob/v3.4.0/peppol-lookup/src/main/java/network/oxalis/vefa/peppol/lookup/locator/BusdoxLocator.java#L109

These exceptions could be caused by a missing/non-registered participant in the network, which is fine and in line with the error message and exception name.

But the exceptions could also be caused by a network level issue at the client, at the DNS-server being used by the client, or somewhere in between. It is very misleading to report these situations as not found.

We hope this issue can prioritized and resolved 👍 

It was previously reported in 2021 to the Oxalis project, and marked as resolved, but it is still present. See https://github.com/OxalisCommunity/oxalis/issues/497

A related issue (but I think not the same) is currently open at https://github.com/OxalisCommunity/oxalis/issues/586

**Comment by pingurunextleft** [comment]
Really important to resolve this! Per Inge Rygg, Vieri

**Comment by canilsenlogiq** [comment]
I believe the changes I did in my pull-request #58 solved a lot of the false-negative lookup results that we where having.

**Comment by aaron-kumar** [comment]
Fixed with release : https://github.com/OxalisCommunity/vefa-peppol/releases/tag/v3.7.0
